version: '3.1'

services:
    virtual-kit-mobile:
        image: nginx:alpine
        build:
            context: .
        ports:
            - 11080:80
        volumes:
            - .:/usr/share/nginx/html
            - ./.docker/nginx.conf:/etc/nginx/nginx.conf
        container_name: virtual-kit-mobile